### ISSUE TITLE
Add --verbose flag

### ISSUE THREAD

**Issue by NightMachinary** [fanzeyi/cargo-play#25]
It's better not to print lines like
```
    Finished release [optimized] target(s) in 0.20s
     Running `/var/folders/5v/g3zxt_7d64g3sd_56bzpqbvh0000gn/T/cargo-play.EcaT1SNHADVuJ2ex5_j0YiUjBv8/target/release/ecat1snhadvuj2ex5_j0yiujbv8
``` 
unless a `--verbose` flag is supplied. Alternatively, add a `--quiet` flag.

**Comment by fanzeyi** [comment]
`--quiet` flag sounds like a good idea. Let me see if I can make it happen.
