### ISSUE TITLE
Implicitly recognize dependencies

### ISSUE THREAD

**Issue by theduke** [fanzeyi/cargo-play#3]
The [Playground](https://play.rust-lang.org/) now supports implicitly adding dependencies by just importing something with `use`.

I think this would be a great addition to this crate.

You could potentially check imports against the crate index and automatically add them as dependencies if they exist.  (There is the https://github.com/frewsxcv/rust-crates-index crate for example that allows this)

**Comment by leo60228** [comment]
I don't think that's what the playground actually does; as far as I'm aware, it just uses a default project with the top 100 Cargo libraries already compiled.

**Comment by fanzeyi** [comment]
@leo60228  Yes, I believe that is the case for Rust Playground. But it doesn't mean we cannot make something like this happen. I already have a WIP version that extracts the external crates from the code and generate Cargo.toml based on it. It won't be perfect but still better than nothing. :P

**Comment by fanzeyi** [comment]
With 8aff17b1929f959ddfecb4d2853c45de8f595366 Cargo-play is now able to recognize dependencies.

**Comment by theduke** [comment]
Awesome!
