### ISSUE TITLE
Add flag to allow disabling compilation and running from cache if exists

### ISSUE THREAD

**Issue by norcalli** [fanzeyi/cargo-play#6]
Add a flag that will skip compilation and run any existing binary. This will reduce startup time for existing scripts.

**Comment by NightMachinary** [comment]
@norcalli What does the current `--cached` do?

**Comment by fanzeyi** [comment]
I believe cargo should already be doing that if there isn't any code changes. If you really don't want to invoke cargo at the beginning, I'd suggest copy the command printed by Cargo.
