### ISSUE TITLE
Allow specifying to build in release mode

### ISSUE THREAD

**Issue by norcalli** [fanzeyi/cargo-play#7]

**Comment by NightMachinary** [comment]
@fanzeyi  Couldn't `--cargo-option` be used for this? I can't quite understand what `--cargo-option` does ...

**Comment by fanzeyi** [comment]
> @fanzeyi  Couldn't `--cargo-option` be used for this? I can't quite understand what `--cargo-option` does ...

That is correct, but I thought turning on release mode would be used more often than other options so I provided a shortcut. For options that are not covered, you can customized with `--cargo-option`.

**Comment by NightMachinary** [comment]
@fanzeyi Can you add an example of using `--cargo-options`? I tried `--cargo-options --release` but this produced errors. Should it be --cargo-options release`?
